### ISSUE TITLE
Unify channel trigger numbering for txt and acq files 

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#118]
Summary
------------
So basically if the file is ``acq`` the first channel is 1 and if the file is``txt`` the first channel is 0.

Additional detail
--------------------
As example, if we start counting from 1, in Test_belt_pulse_multifreq.acq channel 2 is the trigger and therefore the instruction should be written as:
``phys2bids -in phys2bids/phys2bids/tests/data/Test_belt_pulse_multifreq.acq -info -chtrig 2``
whereas in Test_2minRest_trig_multifreq_header_no_comment.txt channel 2 is the trigger also but the instruction is written as:
``phys2bids -in phys2bids/phys2bids/tests/data/Test_2minRest_trig_multifreq_header_no_comment.txt -info -chtrig 1``

Next Steps
-------------
So we need to discuss if channel count starts at 1 or at zero and do the pertaining changes to the file reading functions

**Comment by smoia** [comment]
This is not a bug related to unifying trigger channels, rather than a refactoring of code and a decision on how to deal with particular inputs.

At the moment, the first part of the workflow (the one that is run no matter what) of `phys2bids.py` is:
  1. get the options from the parser
  2. check that the the input file exists and it's supported
  3. populate the blueprint:
     a. read input file
     b. take the trigger channel and move it to element [1] of the channels list
     c. if necessary, extract the information on the time, create a channel as element [0] of the channels list.
  4. Plot the channels and print info.
  5. ...

Now, the problem is that we're returning a misleading information to the user: instead of plotting the original input file, we're returning the populated blueprint in which we scramble the order of the channels. Which might not be the best way to go.
There's also the fact that BIDS doesn't force the file to have a "time" column (because in theory you can reconstruct it with the information in the json), nor the trigger as first column.
I just added this standardisation because I find it easier to work with the data this way: you have an array representing time in the memory, which saves you from computing `np.arange` or similar in those occasion you need it (three times already in phys2bids, once for plotting the channels, once for plotting the trigger, once for the estimation of the starting time) and you have the trigger in a known position (so you can forget about the `channel` parameter).

The other issue is that Labchart txt files can (or do always?) have a column for time as first column in the file. I don't think though that that column is considered a channel in Labchart software (but correct me if I'm wrong), so the user might find having a channel more than expected when running phys2bids.

To summarise, the questions that comes up are (at the very least):
- Should we have an array for time? If not, we can drop column 0 in those txt files that have the time in the first column.
- If we maintain the time array, should we consider that column as a channel ourselves (because it's in the input file) or not (because the user experience will be more similar and intuitive between softwares) when we read labcharts txt files? @RayStick @AyyagariA @kristinazvolanek @BrightMG  you have the most experience with labchart, I guess.
- Should we standardise trigger (and time) positions in our objects?
- If so, should we leave this standardisation outside of the blueprint population? If not, we can just call the function that plots the files and prints the information of the channels on screen inside the blueprint population function.

**Comment by RayStick** [comment]
Firstly, some information, in case it helps to clarify anything:

For LabChart,  if you acquire data channels 1-4, this will be the order they appear when exporting the data to a text file.  The user also has the option to change these things when exporting:
- The channels  they export
 - Header vs no Header 
- Time vs no time column (if yes - becomes first column)
- Date (if yes - becomes second column - or first if no time is requested)
- Comments and Events Markers - not sure how these turn up in the exported data, but I think the user should export without them when possible. We never have them in ours. 

I have noticed that even if there is a ‘Time’ column exported as the first column, the header information does not include this: _ChannelTitle=	Trigger   CO2	O2	Pulse_

Secondly, some responses to questions/queries that were raised (that I understand). Yes, the time column is not a channel in the LabChart software, it is the x axes. If you do not need the time information from the data file itself, then I suggest this time column can just be ignored by phys2bids, and it makes up its own (as sometimes we will have the time column from the data, sometimes not).

**Comment by RayStick** [comment]
I have a (related) thought. If I run:

`phys2bids -in Test_2minRest_trig_multifreq_header_no_comment.txt -info -chtrig 1`

I get:

```
File extension is .txt
Reading the file
Reading infos
File Test_2minRest_trig_multifreq_header_no_comment.txt contains:

00. CO2; sampled at 1000.0 Hz
01. O2; sampled at 1000.0 Hz
02. Belt; sampled at 1000.0 Hz
03. Pulse; sampled at 1000.0 Hz
saving channels plot at plot at Test_2minRest_trig_multifreq_header_no_comment.png
```

Do we want the numbers (e.g. **00**. CO2 and **01**. O2) to reflect the true column numbers? If so, it should be **02**. CO2 and **03**. 02. This is because time is column 1 and trigger is column 2. If time is in the data, it'll always be column 1. If trigger is in the data, it could be any column (though normally the first or second, but it doesn't have to be). Here, the column numbers that are outputted are in order _after_ the trigger, but I am wondering what would happen if the trigger was in the middle column or at the end?

This is only a minor point. Not crucial.

**Comment by RayStick** [comment]
New issues #138 and #137 may be relevant here.
