### ISSUE TITLE
Typos (+ small code suggestion)

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#142]
## Typos
The command line output when calling phys2bids says:
`"saving channels plot at plot at my_phys_outputs/tutorial_file.png"`
This seems to be a typo, and should be something like:
`"saving channel plot to my_phys_outputs/tutorial_file.png"`

The command line output when calling phy2bids with the incorrect threshold says:
`Correcting time offset, assuming missing timepoints are at the beginning (try again with a more liberal thr`
Brackets are not closed, should be:
`Correcting time offset, assuming missing timepoints are at the beginning (try again with a more liberal thr)
`
## Suggestions

The help text in the doc string:
-chplot CHPLOT, --channels-plot CHPLOT
                        path to store channels plot

It was not immediately clear that it wanted the _full_ path, as in the directory and the filename. I actually think it would make more sense to make it only the directory (to match -indir and -outdir) and the name of the file should just be inputfilename_channelplot.png by default.

**Comment by RayStick** [comment]
@vinferrer I assigned you as I think you were made these channel plots, but let me know if not!

**Comment by vinferrer** [comment]
Ups, Thank you @RayStick  sometimes I forgot the little, thought important, details, I think i am gonna solve these on #140 so we don't have to open a PR only for these.

**Comment by RayStick** [comment]
No problem! Yep, that makes sense, to solve them alongside 140.

**Comment by vinferrer** [comment]
I think this should be addressed in the logger #134 PR since that PR is changing all the prints in phys2bids to log commands. @eurunuela is responsible for that PR. To ease his work the first mistake is in line 119 of viz.py:
``"saving channels plot at plot at my_phys_outputs/tutorial_file.png"``
This seems to be a typo, and should be something like:
``"saving channel plot to my_phys_outputs/tutorial_file.png"``

The second mistake i have check and it doesn't belong to viz.py or txt.py maybe this is something @smoia  can clarify where is it?

Lastly I have change the help of -chplot to:
``'full path to store channels plot '`` in #140

**Comment by eurunuela** [comment]
I've taken care of both typos. They should be solved with #134

**Comment by vinferrer** [comment]
Thanks @eurunuela, we should close this when your PR is approved

**Comment by eurunuela** [comment]
I'll merge #134 when #140 is merged.
