### ISSUE TITLE
Make txt test faster

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#172]
## Detailed Description

Test of txt files are very slow due to the amount of downloading and reading of files that happen in each of the testing functions.

## Context / Motivation

Making tests faster would definitely be beneficial for the project.

## Possible Implementation

We could write a helper function that takes care of the downloading of the data and assigns it to variables that are then passed into the testing functions.

**Comment by smoia** [comment]
@eurunuela, I don't know much about helper functions - but I don't understand how this issue might be solved by them. Could you elaborate your idea a bit more?

The reason for which we are downloading the testing file for every test is that:
  1. If we want to run a single test function instead of a whole test file we should be able to do so, and that means we need to be sure the file is there to be tested.
  2. If for some reason a test that is run first messes up with the files we need for a later test, the later test doesn't fail.

An example of 2 is this: `test_1` tests `acq` files, `test_2` tests `txt` files. `test_1` downloads the file `test.acq`, but by mistake it calls it `test.txt`. `test_1` passes anyway, as its input is valid (despite the wrong name). `test_2` tries to download `test.txt`, but as there's already a file with that name, it doesn't download it or downloads it with a different name. Then it fails, as its input is invalid.

Now, it's true that downloading every time the files takes more time, so we could find a way to make it faster. One thing that we could do is to understand what is the minimum content required for our tests, and then create a shorter version of our test files, so that the amount of data downloaded is little and we can make things faster. However, I'd like to know what @RayStick and @rmarkello think about this!

**Comment by vinferrer** [comment]
Yeah I think this is the best approach, I have done the helper thing and it's reducing the testing only 30 seconds, I thing the bottleneck of test_txt.py is the check_multifreq function that is tested every time process_acq or process_lab functions are run. Therefore if we reduce the testing channels file everything could go smothly. What do you think?

**Comment by eurunuela** [comment]
I would reduce the channels file. In the end, this is just a unit test and should make sure the code isn’t broken. Other issues can be found with the integration test.

**Comment by vinferrer** [comment]
Then we should have an OSF folder with the reduced files that we use on the tests

**Comment by smoia** [comment]
@vinferrer  what do youthink about having a file that is quite short (5 minutes), has three channels (so you can test multifreq and onefreq), of which one is the trigger, and has a bit of padding before and after 3-4 TRs?
You can try to craft one with AcqKnowledge (or record it again when we get back to the office), I can help you with that, and maybe @RayStick can provide us a similar file with labchart?

**Comment by rmarkello** [comment]
So out of curiosity I did some quick tests to check how long it takes to run the tests in `test_txt.py`:

```
In [1]: %time test_read_header_and_channels()
CPU times: user 6.37 s, sys: 594 ms, total: 6.96 s
Wall time: 13.9 s

In [2]: %time test_populate_phys_input()
CPU times: user 21.2 s, sys: 954 ms, total: 22.2 s
Wall time: 28.8 s

In [3]: %time test_process_labchart()
CPU times: user 11.2 s, sys: 426 ms, total: 11.7 s
Wall time: 16.8 s

In [4]: %time test_process_acq()
CPU times: user 1min 8s, sys: 1.47 s, total: 1min 9s
Wall time: 1min 13s

In [5]: %time test_raises()
CPU times: user 13.1 s, sys: 852 ms, total: 13.9 s
Wall time: 20.6 s

In [6]: %time test_multifreq()
CPU times: user 1.97 s, sys: 105 ms, total: 2.08 s
Wall time: 4.73 s
```

It looks like `test_process_acq()` is taking, by a wide margin, the longest to run; though, this might just be because that test function has the most calls to `txt.process_acq()` as @vinferrer suggested!

One suggestion I have, in line with @eurunuela's original thought, is to use [`pytest.fixtures`](https://docs.pytest.org/en/latest/fixture.html#fixtures-as-function-arguments) for supplying the correct files to each test function rather than re-downloading them within the functions themselves. For one test, that would look something like:

```python
@pytest.fixture
def samefreq_file():
    url = 'https://osf.io/sdz4n/download'
    test_filename = 'Test_belt_pulse_samefreq.txt'
    test_path = resource_filename('phys2bids', 'tests/data')
    test_full_path = os.path.join(test_path, test_filename)
    wget.download(url, test_full_path)
    return test_full_path


def test_read_header_and_channels(samefreq_file):
    # do all the same stuff, but remove the part where you download the file
    # just replace all the `test_full_path` variable names with `samefreq_file`
```

You could abstract on that concept a bit more and make a data-fetcher function that handles most of the downloading and just accepts a URL and a filename to reduce the repetition of calls to `wget`, too. (It might also be nice for the function to check if the file is already downloaded and simply use that instead of re-downloading!)

All that said, I agree that making the files shorter is probably *also* a good idea! Indeed, it seems like downloading the files really doesn't take very much time (as @vinferrer pointed out!). Still, might as well shave off a bit of time if possible 🤷‍♂

**Comment by RayStick** [comment]
@smoia 

In terms of providing a similar file - I am not sure if I definitely have that exact description of data so would have to record it (which I could not do soon, unfortunately). 

However, on OSF this is close to what you ask: **Test_2minRest_trig_multifreq**
2 minutes, 4 channels, multi frequency, padding before and after

**Comment by smoia** [comment]
@vinferrer what do you think about it?

**Comment by vinferrer** [comment]
I think i am already using Test_2minRest_trig_multifreq for the labchart part. As we talked this morning i can use this file with 3 channels (trigger, channel_with_trigger_freq, channel_diff_freq) so all the test are done properly. My PR will come soon. It will also include changes on the downloading, downloading of files will be done first and then the functions will use the @addparameter functionality to pass parameters used in the asserts.

**Comment by vinferrer** [comment]
I did things a bit differently from what @rmarkello suggested but we can discuss it on the PR
