### ISSUE TITLE
Making terminal output easier to read 

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#196]
## Summary

- This is a very minor issue.  There is quite a lot of text outputted to the terminal, making it hard to focus in on the relevant output (or is it just my tired eyes?!) For example, this is what it is now:

<img width="855" alt="BEFORE" src="https://user-images.githubusercontent.com/50215726/78265791-8a41b800-74ca-11ea-934c-b90ff0b9d98c.png">

Could be something like:

<img width="898" alt="AFTER" src="https://user-images.githubusercontent.com/50215726/78265809-92015c80-74ca-11ea-903b-996ad4de4a83.png">

- Caveat: This will depends on how you are interacting with python. So I guess other people's outputs could look different to mine? However, putting in a space will still make it clearer on any platform, I think.

## Next Steps
- Go through the phys2bids code and locate where there is text that is printed out to screen. Add a tab at the start of each line.

**Comment by RayStick** [comment]
@smoia are you happy with this issue?
@rmarkello do you think this is a good first issue? I have labeled it as such.
I will see if someone else wants to take it but if not I can do it.

**Comment by smoia** [comment]
I really don't know - @eurunuela is the one that implemented the logger!

**Comment by eurunuela** [comment]
I think it could be a good first issue. Wanna give it a try @RayStick ? I’ll be happy to help you 😉

**Comment by rmarkello** [comment]
@RayStick I think this counts! It might be helpful to explain exactly what would need to be changed:

Rather than going through the code and adding a tab (`'\t'`) character to all the calls to `LGR.info` or `LGR.warn`, it might be useful to use [`logger.basicConfig`](https://docs.python.org/3.7/library/logging.html#logging.basicConfig) to ensure the message is always printed with a preprended tab character. There are already some calls to `basicConfig()` in the `phys2bids.py` file: https://github.com/physiopy/phys2bids/blob/07bec6aa41d2cc1a2da4383b8dcf112bf9775734/phys2bids/phys2bids.py#L215-L223

Perhaps modifying them with the `format` parameter would be useful. Something like:

```python
logging.basicConfig(format='%(levelname)s:\t%(message)s')
```

would work! (I'm not positive that's _exactly_ the right syntax, but I think something like that should work.)

**Comment by smoia** [comment]
@RayStick this might not be basic Python, but why don't you share our G1I with the rest of the lab?

**Comment by RayStick** [comment]
@smoia: is G1I = GFI = Good First Issue?

@rmarkello - Great, that seems like a better and more elegant solution. This may be moving away from Good First Issue territory, but that's fine

**Comment by RayStick** [comment]
I've assigned myself to it anyway - I'll give it a go! I want to finish a few python tutorials first, but as this issue does not have a clear deadline, hopefully that'll work out fine.

If I was just putting `'\t'` I could have have definitely managed that ;) but I will try the method suggested by @rmarkello . Therefore, may need some assistance @eurunuela or @rmarkello  - I will let you know.

**Comment by rmarkello** [comment]
More than happy to help, for sure! If you want to take a stab at it and open up a PR we can discuss with references to actual codebits 😄

**Comment by RayStick** [comment]
I can try to rewrite this issue for BrainHack, if that would be welcome?

**Comment by vinferrer** [comment]
If no one does this, I am gonna opena PR and get one more for my hacktoberfest t-shirt

**Comment by RayStick** [comment]
Go for it.
