### ISSUE TITLE
Availabilities for OHBM's standby poster and software demo session?

### ISSUE THREAD

**Issue by sangfrois** [physiopy/phys2bids#233]
# Any volunteers ?
As we discussed during the dev call (June 11th), we need volunteers to attend and represent phys2bids during OHBM. Because the organizers had to consider that people are living in different time zones, it makes it a harder for us to confirm a presence.

# How to confirm your presence
We decided to create a [spreasheet](https://docs.google.com/spreadsheets/d/1oDGfriovi_w7rxz6VXm-0WZLOhyYym-NNWSS64nGtrk/edit?usp=sharing) that sums up the unfolding of the events. 

Under the labels *Poster Standby* and *Software Dem*, find blank cells to write your name in (i.e. if you're available).

Time slots for other events are indicated for information purposes only.

Time zones in green indicate suitable schedule for a given zone.

**Comment by sangfrois** [comment]
(looks like I can't figure out how to add a label to the issue, sorry @smoia)

**Comment by eurunuela** [comment]
Are we assigned the odd or even hours for the poster?

**Comment by rmarkello** [comment]
Even numbers present during the first hour, odds during the second hour. `phys2bids` poster number is 1956.

**Comment by RayStick** [comment]
Thanks @sangfrois. 
I will take a look at what I can sign up for tomorrow morning.

**Comment by rmarkello** [comment]
@physiopy/phys2bids: [here](https://drive.google.com/drive/folders/12SP7b05Hn5NvMEkNyKMYoRAe4Pmx7FIX?usp=sharing) is the first pass at the OHBM poster. I tried to fill up the space as best I could, but suggestions + edits are _definitely_ welcome. Almost all the text is directly copy-pasted from the abstract submission + the documentation because 🤷‍♂️.

@smoia if you want to edit and then distribute to the wider crew via e-mail for approval / sign-off that works, too!

**Please note** I am using some non-standard fonts so if you are going to edit the SVG directly you will need to install:

- [Lato](https://fonts.google.com/specimen/Lato)
- [Roboto](https://fonts.google.com/specimen/Roboto), and
- [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)

before doing so, or else formatting will get all sorts of screwy. Refer to the PDF to see how fonts and formatting should appear. (If you'd like to make suggestions based solely on the PDF I can work to incorporate changes.)

**Comment by smoia** [comment]
Thank you @rmarkello! It looks great!
Would you be able to add a bunch of links to the pdf, so that if people clicks around they redirect to our GItHub page or to the documentation?

**Comment by rmarkello** [comment]
Unfortunately embedding links in SVGs is a pain-in-the-butt / not really viable. 

Currently the allcontributors.org and github.com/physiopy/phys2bids _are_ links, but if you want plain text to actually be a clickable link you'll have to edit the PDF directly and just draw link boxes over the relevant portions of text (in which case you'll only want to do it on the final PDF before upload).

**Comment by eurunuela** [comment]
It looks great! Thanks @rmarkello!

**Comment by RayStick** [comment]
I greyed out the second hour of the poster slot on the spreadsheet, if we are only in the first. (@vicente it looks like you find yourself in a grey box now). The central and eastern times were also mixed up, so I corrected that :)

**Comment by smoia** [comment]
Thinking that the first software demo could see the participation of both EMEA and the Americas, don't be afraid to take that slot even if there is other people!

**Comment by RayStick** [comment]
The poster looks really great @rmarkello 

  Here are some TINY things I noticed (sorry it’s difficult for me to edit it directly right now)  . 

1. If we could subscript the number 2 for CO2 and O2 that’d be great - but not a big deal.
2. (INTRO)Third bullet point should read “but currently no software tools exist **to** convert physiological data into BIDS format”
3. (THE phys2bids SOFTWARE) Third bullet point is missing a space after “will”
4. (How do I collect physiological data? ) Third bullet point - I would remove the “e.g.” before chest position, not fully necessary and it reads better without it. 
5. (What do I do with physiological data?) Could we change the first bullet point to “Ideally you have recorded physiological data throughout the entire scan session (before, after and during each individual scan) and have trigger data to identify when each scan occurred." Though if that makes it too long, it's fine as it is. 

Something about those third bullet points? :)

**Comment by rmarkello** [comment]
@RayStick: third bullet points killing me, apparently! All edits have been incorporated and the newest pdf is uploaded to the previously-linked Google Drive. Thanks for the careful read!

@smoia: do you want to send this out via e-mail to all the PIs and whatnot on the poster to get their (very last minute) approval? Apparently the deadline for poster uploads according to [this OHBM page](https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=4000) is **tomorrow at noon CST (UTC-6)**. I won't have availability to make any more edits / submit before that time frame, so I'm going to leave that to you. Thanks for your efforts ! 💪

**Comment by smoia** [comment]
Thank you @rmarkello! Before I send it to all the authors, can you add somewhere (maybe next to our logo?) an invite to look for our software demo?

**Comment by smoia** [comment]
@all-contributors add @rmarkello for content

**Comment by smoia** [comment]
Ok, this doesn't work. Please remind me to manually add it.

**Comment by AyyagariA** [comment]
I have been MIA with regards to phys2bids but I just looked over the poster and it looks really great! Thank you all for your hard work!

**Comment by rmarkello** [comment]
@smoia just like "look for our software demo!" ?? Is there any info we can give about it (e.g., a number or something)?

**Comment by Berkmann18** [comment]
@all-contributors Please add @rmarkello for content

**Comment by smoia** [comment]
@rmarkello Not that I know of unluckily. I guess the name will be the same as the poster, but for the rest I don't know.

**Comment by smoia** [comment]
@Berkmann18 I'm going to uninstall the bot - really sorry about it but it's quite bothering.

**Comment by Berkmann18** [comment]
@smoia I understand, you can use the CLI tho (at least that one is pretty much up-to-date).

**Comment by smoia** [comment]
@Berkmann18 yes, don't worry! I'm going to try with the CLI!
We can try again the bot at a later date if you want, but as you can see we're very close to some deadlines and we need to focus a bit more.
Thank you for checking out though!

**Comment by Berkmann18** [comment]
@smoia The main problem with the bot (so far) is that it's using an outdated version of the CLI and the latest PR hasn't been merged and I don't have write access for that repo (and seemed to have lost the other rights too) and the 3 others who do don't seem to be spending time getting things moving.

It's fine, I know it can be frustrating to use tools that broke near a deadline so good luck with that.

**Comment by rmarkello** [comment]
@smoia: done! See the updated poster in the Google Drive.

**Comment by RayStick** [comment]
@smoia - are you able to share a link to the software demo? Sorry if you have shared this somewhere but I cannot find it. If I am going to man some of the slots for the conference I want to make sure I am familiar with the content :)

**Comment by smoia** [comment]
@RayStick sorry for the superlate reply.

Some (many) things changed since I recorded the SD, so I'm going to record a new one today or tomorrow. I will then send you all the link to the new one so that you can familiarize with the content.
In the meantime, you can find the current SD version [here](https://drive.google.com/file/d/1b6D_ioeA-RGgNlR3WPF2_PoLA-h6p530/view?usp=sharing)

**Comment by smoia** [comment]
@RayStick long story short I might *not* be able to record another Software Demo. If anyone else wants to do it (you or @eurunuela @vinferrer @sangfrois or anyone else) with the 2.1.0 release, please feel free to. If no one takes care of it and I manage to slide it in I'll try.

**Comment by RayStick** [comment]
No worries! I won't be able to, as I have a bit of catching up to do, to use the latest version of phys2bids (as it seems everyone has been quite busy! 😄)

**Comment by smoia** [comment]
It turns out OHBM platform is... (how can I say it gently) *not the friendliest platform ever made*.

The software demo has a chat. If you're logged into the platform and don't mind being there (even outside of recommended moment), please drop a message in that chat saying you're there. You can also open the jitsi room we use for our meetings and leave the link in the chat.
Please check out the [changelog of version 2.1.0](https://github.com/physiopy/phys2bids/releases/tag/v2.1.0) to know what cool things we do now that are not in the video! 
When you leave, if you're the only one, please send again a  message saying "Hey check us out in GitHub and contact us here or via mail (s.moia@bcbl.eu)". (Tagging @RayStick @sangfrois @eurunuela, since you guys offered to be there).

The poster doesn't have a chat, so you might get contacted independently. I suspect @danalclop will be contacted the most, since he's the first author. If you get contacted (and you don't want to reply to questions), you can redirect people to Gitter or to the Software Demo chat.

**Comment by RayStick** [comment]
Hi Stefano, a few comments/suggestions:

1. Nice demo! It was really clear. 

2. I have watched the demo, read the changelog for version 2.1.0, and also ran the code locally (quite quickly) so should be okay to field general questions about the latest release (but if I am unsure, I will direct people elsewhere).  

3. Does a chat function "open up" when it is actually the poster **time slot** I wonder? Because OHBM said in their instructions to poster presenters _"Once logged in, and during your poster standby tine, attendees will be able to view your PDF and poster and interact with you via a text chat box."_ Do they just mean the generic chat box that is open throughout the whole conference? Well, I guess we'll find out. If it only means that chat feed alongside the poster, I guess we can't really "watch" the poster - we just have to wait until some contacts us.  

      Idea: if it is hard to have a back-and-forth with people, we could open up a GitHub Issue with 'OHBM discussion' 
      and direct people there? Hmm, maybe that is still not the best format, as it's public. Similar to your idea to use jitsi.

4.  After the conference, I plan to try to user test phys2bids 2.1.0 more extensively (and when there is some documentation explaining some of the new featues e.g. I am not sure I understand all the outputs or the new folder structure yet). However, I do have some user feedback on the multi-run functioning so far - I can make a new issue, but is there an appropriate issue already open that would be a good place for me to put my feedback?

**Comment by eurunuela** [comment]
Hey @RayStick 

> 2. I have watched the demo, read the changelog for version 2.1.0, and also ran the code locally (quite quickly) so should be okay to field general questions about the latest release (but if I am unsure, I will direct people elsewhere).
Feel free to direct them to me for latest release-related questions.

> 3. Does a chat function "open up" when it is actually the poster **time slot** I wonder? Because OHBM said in their instructions to poster presenters _"Once logged in, and during your poster standby tine, attendees will be able to view your PDF and poster and interact with you via a text chat box."_ Do they just mean the generic chat box that is open throughout the whole conference? Well, I guess we'll find out. If there is  no chat feed alongside the poster, I guess we can't really "watch" the poster - we just have to wait until someone contacts us.
>    Idea: if it is hard to have a back-and-forth with people, we could open up a GitHub Issue with 'OHBM discussion'
>    and direct people there? Hmm, maybe that is still not the best format, as it's public. Similar to your idea to use jitsi,
>    which is more personal, so probably better.
I guess we'll figure out soon. I'd start with the Gitter chat and move to a GitHub issue if we see it's becoming too difficult to follow. I'd definitely use Jitsi for demoing the software.

> 4. After the conference, I plan to try to user test phys2bids 2.1.0 more extensively (and when there is some documentation explaining some of the new featues e.g. I am not sure I understand all the outputs or the new folder structure yet). However, I do have some user feedback on the multi-run functioning so far - I can make a new issue, but is there an appropriate issue already open that would be a good place for me to put my feedback?
I already opened #265 and think there's no other multirun-related issue open. Open a new one if your comments are not related to #265 😉

**Comment by eurunuela** [comment]
RE chat opening during poster-time: https://twitter.com/OHBM/status/1275817500018704384?s=20

**Comment by RayStick** [comment]
@eurunuela thanks for your replies! I will direct questions your way, if and when they come up. Using Gitter chat then moving to a GitHub issue (if needed) makes sense to me! 

My points are not covered by #265 so I will open a new issue soon!

**Comment by vinferrer** [comment]
@RayStick  Actually we have to update the documentation after the recent changes #264 has a few points we have to update already. You are welcome to suggest moree

**Comment by RayStick** [comment]
Hi all, I was down to cover the software demo today but unfortunately I don’t think I will be able to, sorry. I can still do tomorrow though.

**Comment by eurunuela** [comment]
No problem @RayStick ! Unfortunately, it doesn’t look like many people are checking in lately...

**Comment by RayStick** [comment]
Yeah, that's the impression I got too.

**Comment by smoia** [comment]
Don't despair!
Not a big deal if we don't cover tonight's SD, but @RayStick could you please leave a message in the chat inviting people to engage here, in Gitter, or writing to s.moia@bcbl.eu?

If you can (everyone), please engage on social media and invite people to visit the poster, the SD, and our tools in general!

**Comment by RayStick** [comment]
Yes, I can do that!

**Comment by sangfrois** [comment]
I'm closing this, since we're done with OHBM2020. See you during the next annual meeting 🥇
