### ISSUE TITLE
Add channel plots

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#29]
It's easy to know which channel is which if its timeseries is plotted.
There's already a function to do so in viz.py (plot_channel).

We need to have the function going automatically on all the channels, if the user requires info about the file.

**Comment by smoia** [comment]
![timeseries](https://user-images.githubusercontent.com/35300580/70138881-82474800-1691-11ea-9ec5-6ffe4d591b82.jpg)
I guess something like this could be ok for the moment?

**Comment by vinferrer** [comment]
![image](https://user-images.githubusercontent.com/38909338/70371794-ed825b80-18d7-11ea-9da9-62d660a79a14.png)

Like that?

**Comment by vinferrer** [comment]
@smoia

**Comment by vinferrer** [comment]
Do we have expected ranges in the Y axes or should i leave them free to the channels ?

**Comment by smoia** [comment]
@vinferrer that's a good start, especially because seeing it means being able to deal with the design!
Can you open a *draft* PR with the code you're producing so we can help?

As a general comment:
- We don't need to plot the time (we know it increases), but we can use that channel as a X axis for all the other figures!
- What size is the figure you put here? If it's already 1800x1000 px we need a higher resolution. I guess you're writing this in `viz.py`. If the figure is not 1800x1000 px, that script contains two constant at the beginning, representing fig_size and DPI, can you try to use them for the plots? (Look at how they're used in the other functions in `viz.py` in order to produce that size of figures).

The output you created makes me think that we might want to change the disposition of the plots and/or their content:
1. Instead of having them in two columns, we can stick with one column and X rows so that we can appreciate more their timecourses. 
2. Alternatively, if we want to just give a "preview" for the user to know which channel contains what, we can plot only the first N samples.
3. Another option is that we force the sampling rate to be about 40Hz before plotting, *and only for plotting*. Maybe it helps reducing the noise and clear the figures. Maybe.
@RayStick @BrightMG @CesarCaballeroGaudes @rmarkello , what do you think about it?

**Comment by smoia** [comment]
Also, what file are you using? Maybe it's a full session recording - that would explain the intermittent trigger. In that case, at the moment we don't support them - so we can concentrate on shorter recordings (at the level of runs).

**Comment by vinferrer** [comment]
I was using the txt file you told me to create the txt.py script, i am gonna open a pull request

**Comment by CesarCaballeroGaudes** [comment]
I would let the user specify the sampling rate for plotting, with default values depending on the signal. A sampling rate of 40 Hz might be sufficient for respiratory volume traces, PPG or end-tidal traces, but it might be insufficient for other faster physiological traces such as ECG. 
Second, I would definitely mark the time in the x-axis, otherwise the plot would not be clear. Good plots always have units in all axis.

**Comment by vinferrer** [comment]
time is used for the X axis, as for the units i didn't want to go that far for now but i think ``phys_in`` has units inside.

**Comment by RayStick** [comment]
Looks good! 

Is this a Chicago file? I didn't upload the files so not 100% sure, but it looks like it is. And yes, it is multiple scans which is not supported by the code yet so that's something to consider. If you don't have data for a single scan I can work on getting that to you, or @AyyagariA or @kristinazvolanek can. 

I agree that the time plot is not needed. 

I don't think having units is too crucial at this stage, as they will be different depending on how the recording was set up to record/calibrate (e.g. voltage, %, mmHg). If the units are easy to read in then it's nice to have them but I think just having clear axis labels for now is fine.

**Comment by RayStick** [comment]
I've noticed that we have some Chicago data labelled 'multiscan' and some labelled ' 2minrest' so best to test on the '2minrest' for now. I also added some more data in the Chicago folder - 'Test2'.

**Comment by smoia** [comment]
Closed by #85
