### ISSUE TITLE
Making heuristic functions a simple set of if elif else statements

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#44]
## Detailed Description

At the moment, heuristic files contain a bunch of code that shouldn't be changed by the user (e.g. from [here](https://github.com/smoia/phys2bids/blob/f2d7d52e4e9d9d963f98aeb8809c81660e2f1794/phys2bids/heuristics/heur_test_acq.py#L30)).
It would be better to move that code outside of the heur file, so that the only content of those scripts is a simple definition that reads an input, goes through a bunch of `if` statements to set up the labels necessary for the name of the file, and returns those labels. 

## Context / Motivation

This would simplify the heuristic files on one hand, and help the integration of phys2bids in other BIDSificators programs such as BIDScoin (as in #199).

## Possible Implementation

- Move all the non-`if..elif..else` code into the function [`use_heuristics`](https://github.com/physiopy/phys2bids/blob/8420e44305f17719ff6c49b2f14deb59a6191897/phys2bids/phys2bids.py#L114).

**Comment by rmarkello** [comment]
I think it's _super_ important that we do this—having just run through the documentation before our call, this was one of my first thoughts so I was happy to see it's an issue already! That said, even I'm not totally sure of _how_ this should be implemented, currently. As such, I removed the "good first issue" label from this issue. Let me know if you strongly disagree (I just wanted to provide a brief rationale for why I removed it).

I do think we can take a look at ``heudiconv`` for inspiration as to how they handle their heuristic files! It's been a while since I dug into their codebase so I'm sure it's changed considerably, but last I remember they had some relatively elegant solutions.

**Comment by smoia** [comment]
I see what you mean!
The reason for which I labelled it as a G1I was because what this issue addresses (in my mind) is just moving some lines of code from within the heuristic files to the function that calls them and gets their output. For instance, moving everything after [line 38 of this file](https://github.com/physiopy/phys2bids/blob/27a92bf6595e073b8a462676d2c515b7790b04da/phys2bids/heuristics/heur_tutorial.py#L38), possibly even from line 35, into [this function](https://github.com/physiopy/phys2bids/blob/27a92bf6595e073b8a462676d2c515b7790b04da/phys2bids/phys2bids.py#L114).
The solution could just be changing the heuristic function `return`, the relative variable initialisation in the `use_heuristic` function, and move those lines, so that heuristics are just a pure set of `if elif else` statements.

We will also need to imrpove heuristics in general, but that should come in a different - and definitely _not_ G1I - issue.

**Comment by smoia** [comment]
Now that I see it, we should reopen issue #45 , that is not a duplicate of this one.
