### ISSUE TITLE
Adding documentation on how to use phys2bids

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#47]
Similar to #12 , but we need to explain at least how to:
- [x] Obtain the info of the file in order to set up a real "run" (`-info`)
- [x] Set up an heuristic file (`heur.py`)
- [x] Run the program itself

Before OHBM.

**Comment by eurunuela** [comment]
Any progress on this?

**Comment by RayStick** [comment]
No progress yet. I can work on this 29th - 31st Jan, if that's not too late.

**Comment by RayStick** [comment]
I am working on it this week. 

In terms of example data, I am using mine that I put on OSF:
Test2_time_trigger_CO2_O2_pulse_1000Hz_534TRs.adicht
Test2_time_trigger_CO2_O2_pulse_1000Hz_534TRs.txt
Test2_trigger_CO2_O2_pulse_1000Hz_534TRs.txt

Is this ok, or would people prefer I use the ones in phys2bids/tests/data?

The reason I am not using the ones in tests/data is because I don't know all the details about these files, therefore I cannot be sure that I am getting correct outputs - most importantly, number of TRs.

**Comment by eurunuela** [comment]
I think the OSF data is good. I'd keep the `phys2bids/tests/data` "internal" to run our tests. I believe this would give as a broader range of data to showcase the package, i.e. we'd have more examples.

One could also argue that using the same dataset in all points of the documentation would be easier for users to follow, despite not being the best data for some of the points we'd like to make (?).

**Comment by RayStick** [comment]
Summary from recent call:

@smoia will finish writing the how-to-docs, based on where I got to in my draft PR
Then I will review and edit these how-to-docs, to make sure they make sense to me. 
Then @AyyagariA will use phys2bids, using these docs as a guide, and give us feedback on anything that did not make sense.

**Comment by smoia** [comment]
Update:
I started working on the tutorial, and realised that #156 was more important than I thought, even for the tutorial itself. For this reason, I strongly feel like closing that PR before writing the tutorial (that is being composed anyhow).
