### ISSUE TITLE
phys2bids and/or physiopy logos

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#87]
Maybe this is not the most important point ever, but having a nice figure that represents the work we're doing is incredibly nice.
Luckily, we have a fellow in Donostia that likes doing this sort of things - and does them well!
He sort of volunteered to give us a logo for pys2bids and/or physiopy.
@danalclop wanna take over this issue?

**Comment by eurunuela** [comment]
This may not be the most adequate issue for this but I have just found out there's already a `physiopy`project on GitHub (not an organization though). The developer claims it is a toolbox to simulate physiological data.

Check it out here: https://github.com/jasohill/PhysioPy

**Comment by danalclop** [comment]
Hi everyone!

I built upon the BIDS logo and tried to visualise a simple input-to-output diagram where different sources of "noisy" physiological signal (that's why the left part of the logo is grained) become a clean (grain-free) file system. The color gradient also tries to help transmitting that flow impression.

It's a simple idea, but I think could fit the initial aim of the project. What do you think about it?

![phys2BIDSlogoV 0 2](https://user-images.githubusercontent.com/38854309/70617518-0c9f2700-1c11-11ea-90e1-7687fcad4fe7.png)

**Comment by eurunuela** [comment]
I really like the idea and the logo is cool! 🙌🏻

**Comment by vinferrer** [comment]
This is perfect @danalclop

**Comment by RayStick** [comment]
Looks brilliant!

**Comment by yarikoptic** [comment]
if you remove the folders on the right -- could make it a physiopy logo ;)

**Comment by smoia** [comment]
Actually, I agree with @yarikoptic! Who's in favour to have a slightly modified version of this for physiopy (the organisation)?

**Comment by eurunuela** [comment]
Sounds good! It will not require much work so it's perfect.

**Comment by eurunuela** [comment]
Any update on this @danalclop ?

**Comment by smoia** [comment]
@danalclop, please give us some news?

**Comment by smoia** [comment]
Closed by #170
