### ISSUE TITLE
Phys Data Best Practices Documentation

### ISSUE THREAD

**Issue by AyyagariA** [physiopy/phys2bids#99]
Phys data best practices documentation outline for OHBM abstract [here](https://docs.google.com/document/d/1Lv7jeTk3XnZP9GbNUI7cHs8ZoOuT1NxWrlQIPg6n9Y0/edit?usp=sharing).

Feel free to edit as you see fit.

**Comment by AyyagariA** [comment]
@Everyone Please feel free to look at this document and provide feedback if you want!

**Comment by vinferrer** [comment]
We could add the fact that the data can be plotted with the toolbox for firts inspection, once PR #82 is finish

**Comment by AyyagariA** [comment]
I haven't gotten the file into .rst format yet.

**Comment by smoia** [comment]
Don't worry too much about it. If @rmarkello has a bit of time today or tomorrow, maybe you two can do it together? In any case, abstract is more urgent. If you have time, can you help with the pictures? It's about taking the one @vinferrer showed in his PR #82 , adjust the allcontributors table, and add the logo. Otherwise, I'm going to work on it as soon as I finish with the others

**Comment by AyyagariA** [comment]
Update:
1. The file is in .rst format and is up to date on Github and google docs. 
2. I will work on building this document more fully. @kristinazvolanek if you have time to help over the next few weeks, that would be great!

**Comment by smoia** [comment]
@AyyagariA, @kristinazvolanek, any update?

**Comment by AyyagariA** [comment]
We will have a full document by the end of next week!
